# Custom Application Properties
app.message=Hello from Config Server!
app.support-email=support@example.com
app.max-retry-count=3
app.feature.enable-notifications=true
app.feature.enable-caching=false
app.cache.ttl-seconds=300

# Actuator / Management Endpoints
management.endpoints.web.exposure.include=health,info,env,refresh
management.endpoint.health.show-details=always
management.info.env.enabled=true

